name: Workers_Scale
inputs:
  WORKER_TAG2:
    type: TEXT
    name: Worker tag
    info: Leave empty for no tag
  WORKER_SLOTS2:
    type: TEXT
    name: Number of concurrent slots per worker
    default: "2"
  MAX_WORKERS2:
    type: TEXT
    name: Number of maximum workers
    info: Leave empty to calculate value from concurrent slots in license
  MIN_FREE_SLOTS2:
    type: TEXT
    name: Minimum number of free concurrent slots
    default: "1"
docker_image_name: buddy/workers-scale
docker_image_tag: latest
working_directory: /buddy
execute_commands:
  - . calc.sh
output:
  variables:
    WORKERS:
      example: "2"
      info: Number of workers
    WORKER_SLOTS:
      example: "4"
    WORKER_TAG:
      example: "TAG"